name: take_data_and_update_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  auto_route: ^7.8.4
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.4
  easy_localization: ^3.0.3
  logger: ^2.0.2+1
  easy_logger: ^0.0.2
  kartal: ^3.5.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/util/asset/
  integrations:
    lottie: true
    flutter_svg: true

flutter:

 
  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/lottie/

    

  
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        
  