name: take_data_and_update_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2

  #Navigation
  auto_route: ^7.8.4
  
  #config
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  responsive_framework: ^1.1.1
  connectivity_plus: ^5.0.2
  
  #DataBase
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.4
  
  #Util
  uuid: ^4.2.2
  email_validator: ^2.1.17
  kartal: ^3.5.0
  logger: ^2.0.2+1
  flutter_screenutil: ^5.9.0
  easy_logger: ^0.0.2
  app_settings: ^5.1.1

  #State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
 
 
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.7
  

flutter_gen:
  output: lib/product/util/asset/
  integrations:
    lottie: true
    flutter_svg: true

flutter:

 
  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/translations/
    - assets/.env
    

    

  
  
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Light.ttf
        - asset: assets/fonts/JosefinSans-Medium.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
        
  