// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvQrYthMPLRr1DqoKixHjj0gEYxJNpa34',
    appId: '1:283933501608:web:c7282258d30fef002efa9d',
    messagingSenderId: '283933501608',
    projectId: 'takedataandupdateproject',
    authDomain: 'takedataandupdateproject.firebaseapp.com',
    storageBucket: 'takedataandupdateproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSg2JFxCoK8eDYN1KxJ4807SOBQBLn7vw',
    appId: '1:283933501608:android:cc03dca819869c0c2efa9d',
    messagingSenderId: '283933501608',
    projectId: 'takedataandupdateproject',
    storageBucket: 'takedataandupdateproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKrBegvZDY9OT6SINPUXCysbV1cM4FQJQ',
    appId: '1:283933501608:ios:3cd864adc1da04542efa9d',
    messagingSenderId: '283933501608',
    projectId: 'takedataandupdateproject',
    storageBucket: 'takedataandupdateproject.appspot.com',
    iosBundleId: 'com.example.takeDataAndUpdateProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKrBegvZDY9OT6SINPUXCysbV1cM4FQJQ',
    appId: '1:283933501608:ios:680aa0ba49ed85242efa9d',
    messagingSenderId: '283933501608',
    projectId: 'takedataandupdateproject',
    storageBucket: 'takedataandupdateproject.appspot.com',
    iosBundleId: 'com.example.takeDataAndUpdateProject.RunnerTests',
  );
}
